version: '3.3'
services:

  backend:
    image: arhipvp/foodgram_back:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - postgres_net
      - backend_net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    networks:
      - postgres_net
    
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    networks:
      - backend_net
  
  pgadmin:
    image: dpage/pgadmin4:6
    ports:
      - 5051:80
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=service@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - postgres_net
    depends_on:
      - db
    


volumes:
  static_value:
  media_value:
  postgres_data:
  redoc:
  pgadmin_volume:

networks:
  backend_net:
    driver: bridge
  postgres_net:
    driver: bridge

  