name: Foodgram workflow

on:
   push:
    branches: [master]

jobs:
    
    tests:
        name: PEP8 check
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.8
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip 
              pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
              cd backend/
              pip install -r requirements.txt
          - name: Test with flake8
            run: |
              python -m flake8 backend
    
    build_and_push_backend:
        name: Build and push backend
        runs-on: ubuntu-latest
        needs:
            - tests
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to Docker
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Push to Docker Hub
            uses: docker/build-push-action@v2
            with:
              context: ./backend
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-backend:latest

        
