name: Foodgram workflow

on:
   push:
    branches: [master]

jobs:
    
    tests:
        name: PEP8 check
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.8
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip 
              pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
              cd backend/
              pip install -r requirements.txt
          - name: Test with flake8
            run: |
              python -m flake8 backend